parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/Shared/DTO/'
            - '../src/Infrastructure/Doctrine/Entity/'
            - '../src/Kernel.php'
